baseURL = 'https://hugomvale.github.io/blog/'
locale = 'en-us'
title = 'Blog'
theme = 'PaperMod'

[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)'], ['$', '$']]
